In [1]:
import bz2
import json
import pandas as pd

# 1. Load Event Data (JSON)
with open('FIFA World Cup 2022/Event Data/10510.json', 'rt') as f:
    events_data = json.load(f)

events_df = pd.DataFrame(events_data)

In [2]:
events_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3160 entries, 0 to 3159
Data columns (total 17 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gameId             3160 non-null   int64
 1   gameEventId        3160 non-null   int64
 2   possessionEventId  1917 non-null   float64
 3   startTime          3160 non-null   float64
 4   endTime            3032 non-null   float64
 5   duration           3160 non-null   float64
 6   eventTime          3160 non-null   float64
 7   sequence           3018 non-null   float64
 8   gameEvents         3160 non-null   object
 9   initialTouch       3160 non-null   object
 10  possessionEvents   3160 non-null   object
 11  fouls              3160 non-null   object
 12  grades             3160 non-null   object
 13  stadiumMetadata    3160 non-null   object
 14  homePlayers        3160 non-null   object
 15  awayPlayers        3160 non-null   object
 16  ball               3160 non-null   object
dtypes: float64(6), int64(2), object(9)
memory usage: 419.8+ KB

In [3]:
events_df.head(1)

,gameId,gameEventId,possessionEventId,startTime,endTime,duration,eventTime,sequence,gameEvents,initialTouch,possessionEvents,fouls,grades,stadiumMetadata,homePlayers,awayPlayers,ball
0,10510,6662332,6545591.0,180.314,180.314,0.0,180.314,1.0,"{'gameEventType': 'FIRSTKICKOFF', 'initialNonE...","{'initialBodyType': 'R', 'initialHeightType': ...","{'possessionEventType': 'PA', 'nonEvent': Fals...","{'onFieldCulpritPlayerId': None, 'onFieldCulpr...","{'additionalDuelerGrade': None, 'awayDuelGrade...","{'stadiumId': 189, 'stadiumName': 'Education C...","[{'jerseyNum': 8, 'confidence': 'HIGH', 'visib...","[{'jerseyNum': 14, 'confidence': 'LOW', 'visib...","[{'visibility': 'VISIBLE', 'x': -1.18, 'y': 0...."

In [4]:
# Set no limit for rows
pd.set_option('display.max_rows', None)

# Set no limit for columns
pd.set_option('display.max_columns', None)

# Show up to 500 characters per cell
pd.set_option('display.max_colwidth', 500)

# Show the full content regardless of length
pd.set_option('display.max_colwidth', None)

In [5]:
# 1. Expand the list of dictionaries into a separate DataFrame
expanded_df = pd.json_normalize(events_df['initialTouch'])

# 2. Drop columns where ALL values are NaN/None
expanded_df = expanded_df.dropna(axis=1, how='all')

# 3. Print the value counts for the remaining valid columns
for col in expanded_df.columns:
    if len(expanded_df[col].value_counts(dropna=True)) > 11:
        continue
    print(f"========== {col} ==========")
    print(expanded_df[col].value_counts(dropna=True))
    print("\n")

========== initialHeightType ==========
initialHeightType
G    2310
L     367
V     172
A     167
H      90
M      54
Name: count, dtype: int64


========== facingType ==========
facingType
G    3160
Name: count, dtype: int64


========== initialTouchType ==========
initialTouchType
S    2965
M      33
B      12
G       8
Name: count, dtype: int64


========== initialPressureType ==========
initialPressureType
N    2518
P     451
A      48
L       1
Name: count, dtype: int64

In [6]:
# 1. Expand the list of dictionaries into a separate DataFrame
expanded_df = pd.json_normalize(events_df['possessionEvents'])

# 2. Drop columns where ALL values are NaN/None
expanded_df = expanded_df.dropna(axis=1, how='all')

# 3. Print the value counts for the remaining valid columns
for col in expanded_df.columns:
    if len(expanded_df[col].value_counts(dropna=True)) > 11:
        continue
    print(f"========== {col} ==========")
    print(expanded_df[col].value_counts(dropna=True))
    print("\n")

========== possessionEventType ==========
possessionEventType
PA    1427
IT    1094
CH     258
RE      58
CL      58
CR      48
SH      39
TC      18
BC      11
Name: count, dtype: int64


========== nonEvent ==========
nonEvent
False    1891
True       26
Name: count, dtype: int64


========== ballHeightType ==========
ballHeightType
G    1303
L      96
A      96
V      50
M      14
H      12
Name: count, dtype: int64


========== highPointType ==========
highPointType
G    931
A    316
L    239
H     54
M     50
Name: count, dtype: int64


========== passType ==========
passType
S    1303
C      50
T      31
O      23
F      16
B       4
Name: count, dtype: int64


========== passOutcomeType ==========
passOutcomeType
C    1265
D     112
B      29
S      12
O       9
Name: count, dtype: int64


========== crossType ==========
crossType
O    24
I    17
P     4
D     3
Name: count, dtype: int64


========== crossZoneType ==========
crossZoneType
C    19
F    13
N    12
S     4
Name: count, dtype: int64


========== crossOutcomeType ==========
crossOutcomeType
D    27
C    11
B     5
O     3
U     2
Name: count, dtype: int64


========== targetFacingType ==========
targetFacingType
G    698
L    371
B    358
Name: count, dtype: int64


========== receiverFacingType ==========
receiverFacingType
G    613
L    343
B    301
Name: count, dtype: int64


========== deflectorPlayerId ==========
deflectorPlayerId
1683.0     3
3930.0     1
8129.0     1
3846.0     1
13861.0    1
Name: count, dtype: int64


========== deflectorPlayerName ==========
deflectorPlayerName
Casemiro            3
Lucas Paquetá       1
Marcelo Brozovic    1
Marquinhos          1
Bruno Petkovic      1
Name: count, dtype: int64


========== failedBlocker2PlayerId ==========
failedBlocker2PlayerId
1697.0     1
8039.0     1
13830.0    1
Name: count, dtype: int64


========== failedBlocker2PlayerName ==========
failedBlocker2PlayerName
Rodrygo    1
Antony     1
Pedro      1
Name: count, dtype: int64


========== accuracyType ==========
accuracyType
S    1225
R      21
C       9
H       9
L       7
P       5
Name: count, dtype: int64


========== linesBrokenType ==========
linesBrokenType
A     54
M     50
D     15
AM     6
MD     4
Name: count, dtype: int64


========== bodyMovementType ==========
bodyMovementType
TG    25
LA     9
ST     3
AG     2
Name: count, dtype: int64


========== ballMoving ==========
ballMoving
True     29
False    10
Name: count, dtype: int64


========== shotType ==========
shotType
S    28
F     7
V     4
Name: count, dtype: int64


========== shotNatureType ==========
shotNatureType
A    22
P    16
F     1
Name: count, dtype: int64


========== shotInitialHeightType ==========
shotInitialHeightType
BOTTOMTHIRD    17
MIDDLETHIRD    11
G               4
O               4
TOPTHIRD        3
F               1
Name: count, dtype: int64


========== shotOutcomeType ==========
shotOutcomeType
S    13
B    10
O     9
G     8
Name: count, dtype: int64


========== keeperPlayerId ==========
keeperPlayerId
13854.0    15
32.0        5
Name: count, dtype: int64


========== keeperPlayerName ==========
keeperPlayerName
Dominik Livakovic    15
Alisson               5
Name: count, dtype: int64


========== saveHeightType ==========
saveHeightType
BOTTOMTHIRD    8
MIDDLETHIRD    4
G              1
Name: count, dtype: int64


========== saveReboundType ==========
saveReboundType
RO    1
LA    1
HL    1
GL    1
M6    1
L6    1
MA    1
Name: count, dtype: int64


========== badParry ==========
badParry
False    13
Name: count, dtype: int64


========== saveable ==========
saveable
True    3
Name: count, dtype: int64


========== clearanceOutcomeType ==========
clearanceOutcomeType
P    43
O     8
S     4
B     2
D     1
Name: count, dtype: int64


========== challengeType ==========
challengeType
B        67
D        52
A        41
FIFTY    34
T        34
S        17
H         9
L         4
Name: count, dtype: int64


========== dribbleType ==========
dribbleType
O    19
I    15
T    10
K     8
B     1
Name: count, dtype: int64


========== tackleAttemptType ==========
tackleAttemptType
G    32
T    20
D     1
Name: count, dtype: int64


========== trickType ==========
trickType
F    5
N    4
S    1
Name: count, dtype: int64


========== additionalDuelerPlayerId ==========
additionalDuelerPlayerId
1687.0    1
Name: count, dtype: int64


========== additionalDuelerPlayerName ==========
additionalDuelerPlayerName
Luka Modric    1
Name: count, dtype: int64


========== challengeOutcomeType ==========
challengeOutcomeType
R    75
P    54
D    48
F    44
O    11
C     7
M     6
K     6
N     3
S     2
L     2
Name: count, dtype: int64


========== carryType ==========
carryType
C    6
B    5
Name: count, dtype: int64


========== ballCarryOutcome ==========
ballCarryOutcome
R    9
L    2
Name: count, dtype: int64


========== carryDefenderPlayerId ==========
carryDefenderPlayerId
195.0     4
3865.0    1
8136.0    1
2074.0    1
1676.0    1
3930.0    1
1683.0    1
100.0     1
Name: count, dtype: int64


========== carryDefenderPlayerName ==========
carryDefenderPlayerName
Richarlison      4
Neymar           1
Ivan Perisic     1
Raphinha         1
Eder Militao     1
Lucas Paquetá    1
Casemiro         1
Mateo Kovacic    1
Name: count, dtype: int64


========== carryIntent ==========
carryIntent
B    5
E    4
Name: count, dtype: int64


========== touchType ==========
touchType
F    13
H     6
T     1
Name: count, dtype: int64


========== touchOutcomeType ==========
touchOutcomeType
P    11
C     6
O     3
Name: count, dtype: int64


========== originateType ==========
originateType
P    58
Name: count, dtype: int64


========== reboundOutcomeType ==========
reboundOutcomeType
P    42
T    15
Name: count, dtype: int64


========== missedTouchType ==========
missedTouchType
M    8
S    1
D    1
Name: count, dtype: int64


========== missedTouchPlayerId ==========
missedTouchPlayerId
3865.0     3
13858.0    1
8330.0     1
8136.0     1
1697.0     1
1683.0     1
1676.0     1
13830.0    1
Name: count, dtype: int64


========== missedTouchPlayerName ==========
missedTouchPlayerName
Neymar             3
Josip Juranovic    1
Mario Pasalic      1
Ivan Perisic       1
Rodrygo            1
Casemiro           1
Eder Militao       1
Pedro              1
Name: count, dtype: int64


========== pressureType ==========
pressureType
N    932
P    792
A    115
L     78
Name: count, dtype: int64


========== opportunityType ==========
opportunityType
D    44
P    12
H     7
N     1
C     1
Name: count, dtype: int64


========== betterOptionType ==========
betterOptionType
C    6
P    3
B    2
Name: count, dtype: int64


========== betterOptionPlayerId ==========
betterOptionPlayerId
8330.0     1
3865.0     1
4926.0     1
8136.0     1
13861.0    1
Name: count, dtype: int64


========== betterOptionPlayerName ==========
betterOptionPlayerName
Mario Pasalic     1
Neymar            1
Borna Sosa        1
Ivan Perisic      1
Bruno Petkovic    1
Name: count, dtype: int64


========== createsSpace ==========
createsSpace
False    1541
True       31
Name: count, dtype: int64


========== closingDownPlayerId ==========
closingDownPlayerId
1695.0    1
1683.0    1
Name: count, dtype: int64


========== closingDownPlayerName ==========
closingDownPlayerName
Vinícius Junior    1
Casemiro           1
Name: count, dtype: int64


========== dabPlayerId ==========
dabPlayerId
4926.0    1
8050.0    1
Name: count, dtype: int64


========== dabPlayerName ==========
dabPlayerName
Borna Sosa     1
Alex Sandro    1
Name: count, dtype: int64


========== movementPlayerId ==========
movementPlayerId
8136.0    1
4883.0    1
1695.0    1
1676.0    1
Name: count, dtype: int64


========== movementPlayerName ==========
movementPlayerName
Ivan Perisic       1
Andrej Kramaric    1
Vinícius Junior    1
Eder Militao       1
Name: count, dtype: int64


========== disciplinePlayerId ==========
disciplinePlayerId
13861.0    1
Name: count, dtype: int64


========== disciplinePlayerName ==========
disciplinePlayerName
Bruno Petkovic    1
Name: count, dtype: int64

In [7]:
# 1. Expand the list of dictionaries into a separate DataFrame
expanded_df = pd.json_normalize(events_df['gameEvents'])

# 2. Drop columns where ALL values are NaN/None
expanded_df = expanded_df.dropna(axis=1, how='all')

# 3. Print the value counts for the remaining valid columns
for col in expanded_df.columns:
    if len(expanded_df[col].value_counts(dropna=True)) > 11:
        continue
    print(f"========== {col} ==========")
    print(expanded_df[col].value_counts(dropna=True))
    print("\n")

========== gameEventType ==========
gameEventType
OTB              3014
OUT               127
SUB                10
END                 4
FIRSTKICKOFF        1
SECONDKICKOFF       1
THIRDKICKOFF        1
FOURTHKICKOFF       1
G                   1
Name: count, dtype: int64


========== initialNonEvent ==========
initialNonEvent
False    3131
True       29
Name: count, dtype: int64


========== period ==========
period
2    1235
1    1187
3     400
4     338
Name: count, dtype: int64


========== videoMissing ==========
videoMissing
False    3047
True      113
Name: count, dtype: int64


========== teamId ==========
teamId
361.0    1522
371.0    1486
Name: count, dtype: int64


========== teamName ==========
teamName
Brazil     1522
Croatia    1486
Name: count, dtype: int64


========== homeTeam ==========
homeTeam
False    1522
True     1486
Name: count, dtype: int64


========== touches ==========
touches
2.0     1065
1.0      753
3.0      571
4.0      294
5.0      163
6.0       66
7.0       45
8.0       29
9.0       15
10.0       4
11.0       2
Name: count, dtype: int64


========== touchesInBox ==========
touchesInBox
0.0    2909
1.0      68
2.0      19
3.0      14
4.0       6
5.0       2
Name: count, dtype: int64


========== setpieceType ==========
setpieceType
O    2886
F      54
T      36
G      17
C      10
P       8
K       6
D       1
Name: count, dtype: int64


========== earlyDistribution ==========
earlyDistribution
False    3011
True        7
Name: count, dtype: int64


========== endType ==========
endType
FIRST     1
SECOND    1
F         1
G         1
Name: count, dtype: int64


========== outType ==========
outType
T    63
W    56
H     5
A     3
Name: count, dtype: int64


========== subType ==========
subType
S    10
Name: count, dtype: int64


========== playerOffId ==========
playerOffId
2074.0    1
1695.0    1
4883.0    1
8330.0    1
195.0     1
1676.0    1
100.0     1
3930.0    1
4926.0    1
8129.0    1
Name: count, dtype: int64


========== playerOffName ==========
playerOffName
Raphinha            1
Vinícius Junior     1
Andrej Kramaric     1
Mario Pasalic       1
Richarlison         1
Eder Militao        1
Mateo Kovacic       1
Lucas Paquetá       1
Borna Sosa          1
Marcelo Brozovic    1
Name: count, dtype: int64


========== playerOnId ==========
playerOnId
8039.0     1
1697.0     1
13861.0    1
6019.0     1
13830.0    1
8050.0     1
5968.0     1
132.0      1
1665.0     1
13859.0    1
Name: count, dtype: int64


========== playerOnName ==========
playerOnName
Antony            1
Rodrygo           1
Bruno Petkovic    1
Nikola Vlasic     1
Pedro             1
Alex Sandro       1
Lovro Majer       1
Fred              1
Ante Budimir      1
Mislav Orsic      1
Name: count, dtype: int64

In [8]:
# 1. Expand the list of dictionaries into a separate DataFrame
expanded_df = pd.json_normalize(events_df['fouls'])

# 2. Drop columns where ALL values are NaN/None
expanded_df = expanded_df.dropna(axis=1, how='all')

# 3. Print the value counts for the remaining valid columns
for col in expanded_df.columns:
    if len(expanded_df[col].value_counts(dropna=True)) > 11:
        continue
    print(f"========== {col} ==========")
    print(expanded_df[col].value_counts(dropna=True))
    print("\n")

========== foulType ==========
foulType
I    53
M     4
A     2
Name: count, dtype: int64


========== onFieldOffenseType ==========
onFieldOffenseType
N    47
O     6
H     3
V     1
T     1
F     1
Name: count, dtype: int64


========== finalOffenseType ==========
finalOffenseType
N    47
O     6
H     3
V     1
T     1
F     1
Name: count, dtype: int64


========== onFieldFoulOutcomeType ==========
onFieldFoulOutcomeType
N    50
Y     5
F     4
Name: count, dtype: int64


========== finalFoulOutcomeType ==========
finalFoulOutcomeType
N    50
Y     5
F     4
Name: count, dtype: int64


========== var ==========
var
False    59
Name: count, dtype: int64


========== correctDecision ==========
correctDecision
True     55
False     4
Name: count, dtype: int64

In [9]:
# 1. Expand the list of dictionaries into a separate DataFrame
expanded_df = pd.json_normalize(events_df['grades'])

# 2. Drop columns where ALL values are NaN/None
expanded_df = expanded_df.dropna(axis=1, how='all')

# 3. Print the value counts for the remaining valid columns
for col in expanded_df.columns:
    if len(expanded_df[col].value_counts(dropna=True)) > 11:
        continue
    print(f"========== {col} ==========")
    print(expanded_df[col].value_counts(dropna=True))
    print("\n")

========== additionalDuelerGrade ==========
additionalDuelerGrade
-0.5    1
Name: count, dtype: int64


========== awayDuelGrade ==========
awayDuelGrade
 0.5    28
-0.5    25
 0.0    17
-1.0     4
 1.0     1
Name: count, dtype: int64


========== ballCarrierGrade ==========
ballCarrierGrade
 0.0    8
-0.5    2
 0.5    1
Name: count, dtype: int64


========== blockerGrade ==========
blockerGrade
0.5    29
0.0    16
Name: count, dtype: int64


========== carrierGrade ==========
carrierGrade
 0.0    72
-0.5    52
 0.5     7
Name: count, dtype: int64


========== carryDefenderGrade ==========
carryDefenderGrade
 0.0    8
-0.5    3
Name: count, dtype: int64


========== challengerGrade ==========
challengerGrade
 0.0    70
-0.5    58
 0.5    50
-1.0     4
 1.0     1
Name: count, dtype: int64


========== clearerGrade ==========
clearerGrade
 0.0    46
-0.5     9
-1.0     1
-1.5     1
 0.5     1
Name: count, dtype: int64


========== closingDownGrade ==========
closingDownGrade
-0.5    2
Name: count, dtype: int64


========== crosserGrade ==========
crosserGrade
-0.5    18
 0.0    18
 0.5     6
-1.0     6
Name: count, dtype: int64


========== dabGrade ==========
dabGrade
 0.5    1
-0.5    1
Name: count, dtype: int64


========== defenderGrade ==========
defenderGrade
0.0    131
0.5      8
Name: count, dtype: int64


========== deflectorGrade ==========
deflectorGrade
0.0    7
Name: count, dtype: int64


========== disciplineGrade ==========
disciplineGrade
-0.5    1
Name: count, dtype: int64


========== dribblerGrade ==========
dribblerGrade
-0.5    23
 0.5    19
 0.0     9
 1.0     1
Name: count, dtype: int64


========== failedBlockerGrade ==========
failedBlockerGrade
 0.0    142
-0.5      1
Name: count, dtype: int64


========== failedBlocker2Grade ==========
failedBlocker2Grade
0.0    3
Name: count, dtype: int64


========== homeDuelGrade ==========
homeDuelGrade
-0.5    32
 0.5    22
 0.0    17
 1.0     2
-1.0     2
Name: count, dtype: int64


========== keeperGrade ==========
keeperGrade
0.0    18
0.5     3
Name: count, dtype: int64


========== movementGrade ==========
movementGrade
 0.0    2
-0.5    1
 0.5    1
Name: count, dtype: int64


========== passerGrade ==========
passerGrade
 0.0    1321
-0.5      77
 0.5      23
-1.0       6
Name: count, dtype: int64


========== positionGrade ==========
positionGrade
-0.5    13
-1.0     4
Name: count, dtype: int64


========== receiverGrade ==========
receiverGrade
 0.0    1272
-0.5       3
 0.5       1
Name: count, dtype: int64


========== shooterGrade ==========
shooterGrade
 0.0    18
-0.5    11
-1.0     6
 0.5     3
 1.0     1
Name: count, dtype: int64


========== targetGrade ==========
targetGrade
 0.0    164
-0.5      6
Name: count, dtype: int64


========== touchGrade ==========
touchGrade
-0.5    17
 0.0     8
-1.0     1
Name: count, dtype: int64

In [10]:
# 1. Expand the list of dictionaries into a separate DataFrame
expanded_df = pd.json_normalize(events_df['stadiumMetadata'])

# 2. Drop columns where ALL values are NaN/None
expanded_df = expanded_df.dropna(axis=1, how='all')

# 3. Print the value counts for the remaining valid columns
for col in expanded_df.columns:
    if len(expanded_df[col].value_counts(dropna=True)) > 11:
        continue
    print(f"========== {col} ==========")
    print(expanded_df[col].value_counts(dropna=True))
    print("\n")

========== stadiumId ==========
stadiumId
189    3160
Name: count, dtype: int64


========== stadiumName ==========
stadiumName
Education City Stadium    3160
Name: count, dtype: int64


========== pitchLength ==========
pitchLength
105.0    3160
Name: count, dtype: int64


========== pitchWidth ==========
pitchWidth
68.0    3160
Name: count, dtype: int64


========== homeTeamStartLeft ==========
homeTeamStartLeft
True    3160
Name: count, dtype: int64


========== homeTeamStartLeftExtraTime ==========
homeTeamStartLeftExtraTime
True    3160
Name: count, dtype: int64


========== teamAttackingDirection ==========
teamAttackingDirection
L      1632
R      1376
nan     152
Name: count, dtype: int64

In [11]:
events_df['homePlayers'][1]

[{'jerseyNum': 8,
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': -3.509,
  'y': 10.558,
  'speed': 0.117,
  'playerId': 100,
  'positionGroupType': 'CM'},
 {'jerseyNum': 1,
  'confidence': 'LOW',
  'visibility': 'ESTIMATED',
  'x': -38.502,
  'y': 0.272,
  'speed': 0.644,
  'playerId': 13854,
  'positionGroupType': 'GK'},
 {'jerseyNum': 22,
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': 2.431,
  'y': -28.122,
  'speed': 4.686,
  'playerId': 13858,
  'positionGroupType': 'RB'},
 {'jerseyNum': 10,
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': 2.48,
  'y': 0.321,
  'speed': 3.687,
  'playerId': 1687,
  'positionGroupType': 'CM'},
 {'jerseyNum': 6,
  'confidence': 'LOW',
  'visibility': 'ESTIMATED',
  'x': -16.415,
  'y': -6.513,
  'speed': 1.502,
  'playerId': 40,
  'positionGroupType': 'RCB'},
 {'jerseyNum': 9,
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': 4.052,
  'y': -10.981,
  'speed': 4.99,
  'playerId': 4883,
  'positionGroupType': 'CF'},
 {'jerseyNum': 20,
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': -18.287,
  'y': 5.976,
  'speed': 1.52,
  'playerId': 4892,
  'positionGroupType': 'LCB'},
 {'jerseyNum': 19,
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': -13.437,
  'y': 21.793,
  'speed': 1.394,
  'playerId': 4926,
  'positionGroupType': 'LB'},
 {'jerseyNum': 11,
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': -10.636,
  'y': 1.4,
  'speed': 0.605,
  'playerId': 8129,
  'positionGroupType': 'CM'},
 {'jerseyNum': 4,
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': 1.408,
  'y': 16.059,
  'speed': 3.42,
  'playerId': 8136,
  'positionGroupType': 'LW'},
 {'jerseyNum': 15,
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': 3.864,
  'y': -19.08,
  'speed': 5.449,
  'playerId': 8330,
  'positionGroupType': 'RW'}]

In [12]:
events_df['ball'][1]

[{'visibility': 'VISIBLE', 'x': -9.53, 'y': 0.69, 'z': 0.0}]

In [13]:
# Group by sequence to find the start of the first event and end of the last event
sequences = events_df.groupby('sequence').agg(
    start_time=('startTime', 'min'),
    end_time=('endTime', 'max')
).reset_index()
sequences

     sequence  start_time  end_time
0         1.0     180.314   188.622
1         2.0     190.557   190.557
2         3.0     195.162   233.166
3         4.0     248.348   250.484
4         5.0     266.033   270.170
5         6.0     271.038   301.201
6         7.0     302.269   302.269
7         8.0     303.136   303.904
8         9.0     304.605   307.808
9        10.0     329.463   344.545
10       11.0     348.015   348.015
11       12.0     350.350   362.062
12       13.0     362.062   363.730
13       14.0     376.844   426.126
14       15.0     427.227   447.714
15       16.0     449.349   449.349
16       17.0     450.584   450.584
17       18.0     452.586   454.488
18       19.0     476.410   479.813
19       20.0     479.813   481.215
20       21.0     482.683   498.131
21       22.0     499.533   505.372
22       23.0     504.371   509.510
23       24.0     529.062   537.671
24       25.0     538.405   590.724
25       26.0     605.639   615.148
26       27.0     631.064   649.149
27       28.0     651.118   659.159
28       29.0     660.861   662.896
29       30.0     671.839   681.915
30       31.0     682.482   695.395
31       32.0     700.534   751.451
32       33.0     752.152   752.152
33       34.0     782.749   786.320
34       35.0     789.056   810.210
35       36.0     828.295   839.305
36       37.0     839.305   861.962
37       38.0     877.110   904.071
38       39.0     951.051   962.296
39       40.0     964.698   968.335
40       41.0    1003.103  1014.982
41       42.0    1019.086  1023.190
42       43.0    1024.958  1031.999
43       44.0    1035.202  1037.571
44       45.0    1058.659  1106.874
45       46.0    1123.156  1140.440
46       47.0    1141.208  1203.036
47       48.0    1204.004  1217.551
48       49.0    1223.957  1243.611
49       50.0    1244.178  1244.178
50       51.0    1250.517  1258.559
51       52.0    1258.559  1322.956
52       53.0    1325.092  1385.018
53       54.0    1385.552  1406.840
54       55.0    1410.811  1417.050
55       56.0    1419.553  1440.407
56       57.0    1444.111  1464.198
57       58.0    1465.399  1493.760
58       59.0    1497.364  1537.771
59       60.0    1568.802  1569.903
60       61.0    1571.004  1571.004
61       62.0    1573.307  1573.307
62       63.0    1589.857  1626.159
63       64.0    1702.236  1705.205
64       65.0    1720.954  1768.602
65       66.0    1770.070  1772.706
66       67.0    1773.440  1774.942
67       68.0    1774.942  1774.942
68       69.0    1776.009  1776.009
69       70.0    1776.844  1778.679
70       71.0    1779.379  1780.214
71       72.0    1780.214  1788.055
72       73.0    1790.691  1805.472
73       74.0    1806.840  1814.348
74       75.0    1835.435  1836.837
75       76.0    1838.906  1840.174
76       77.0    1891.592  1925.025
77       78.0    1926.026  1947.381
78       79.0    1967.568  1995.028
79       80.0    2035.235  2038.972
80       81.0    2041.041  2048.248
81       82.0    2053.086  2053.086
82       83.0    2054.721  2065.065
83       84.0    2080.781  2105.873
84       85.0    2110.177  2115.415
85       86.0    2117.651  2148.549
86       87.0    2148.549  2152.653
87       88.0    2153.387  2257.891
88       89.0    2259.293  2271.271
89       90.0    2273.373  2276.243
90       91.0    2287.554  2319.920
91       92.0    2321.154  2325.425
92       93.0    2342.509  2348.148
93       94.0    2350.751  2352.653
94       95.0    2355.155  2395.929
95       96.0    2417.551  2425.359
96       97.0    2430.697  2465.866
97       98.0    2466.900  2471.772
98       99.0    2472.172  2476.743
99      100.0    2477.644  2529.696
100     101.0    2531.565  2535.369
101     102.0    2540.374  2597.064
102     103.0    2597.564  2599.733
103     104.0    2600.901  2600.901
104     105.0    2673.674  2673.674
105     106.0    2674.808  2758.559
106     107.0    2761.261  2765.499
107     108.0    2768.168  2771.371
108     109.0    2812.312  2825.692
109     110.0    2845.512  2848.248
110     111.0    2866.867  2872.639
111     112.0    2874.641  2875.375
112     113.0    2886.186  2907.875
113     114.0    2909.209  2911.712
114     115.0    2912.513  2927.461
115     116.0    2942.042  2942.042
116     117.0    2981.148  2987.988
117     118.0    2996.563  3004.371
118     119.0    3005.172  3009.009
119     120.0    3038.805  3042.309
120     121.0    3044.211  3049.816
121     122.0    3067.000  3083.016
122     123.0    3084.952  3084.952
123     124.0    3085.886  3094.328
124     125.0    3100.901  3122.322
125     126.0    3196.163  3250.384
126     127.0    3282.749  3286.987
127     128.0    3287.387  3288.355
128     129.0    3301.702  3325.292
129     130.0    3332.966  3336.036
130     131.0    3336.803  3338.739
131     132.0    3356.390  3364.798
132     133.0    3366.099  3383.750
133     134.0    3384.218  3389.056
134     135.0    3399.233  3412.779
135     136.0    3415.148  3418.986
136     137.0    3422.022  3440.340
137     138.0    3440.707  3457.457
138     139.0    3474.608  3624.291
139     140.0    3625.025  3625.025
140     141.0    3625.692  3631.298
141     142.0    3634.067  3634.067
142     143.0    3635.702  3635.702
143     144.0    3647.948  3763.797
144     145.0    3765.599  3771.872
145     146.0    3774.074  3778.712
146     147.0    3781.114  3799.800
147     148.0    3826.226  3848.382
148     149.0    3849.550  3873.740
149     150.0    3874.341  3942.209
150     151.0    3943.110  3955.022
151     152.0    3956.123  3999.066
152     153.0    4000.267  4150.817
153     154.0    4189.723  4190.090
154     155.0    4197.698  4213.080
155     156.0    4234.902  4247.981
156     157.0    4249.750  4253.487
157     158.0    4255.055  4308.675
158     159.0    4311.478  4322.155
159     160.0    4357.991  4380.714
160     161.0    4382.983  4406.440
161     162.0    4407.908  4427.528
162     163.0    4436.770  4478.478
163     164.0    4485.052  4539.039
164     165.0    4542.075  4542.075
165     166.0    4608.275  4659.993
166     167.0    4661.061  4667.467
167     168.0    4668.769  4675.742
168     169.0    4684.218  4696.296
169     170.0    4698.232  4751.952
170     171.0    4763.730  4767.668
171     172.0    4784.418  4786.753
172     173.0    4788.655  4796.797
173     174.0    4796.797  4796.797
174     175.0    4798.365  4815.415
175     176.0    4815.415  4815.415
176     177.0    4818.218  4818.218
177     178.0    4820.153  4828.862
178     179.0    4851.185  4852.553
179     180.0    4854.221  4860.060
180     181.0    4883.517  4892.926
181     182.0    4911.478  4948.182
182     183.0    4947.848  4954.421
183     184.0    4975.275  4994.061
184     185.0    4995.229  5025.692
185     186.0    5026.527  5035.269
186     187.0    5037.604  5067.868
187     188.0    5068.502  5109.910
188     189.0    5111.044  5155.589
189     190.0    5158.158  5176.476
190     191.0    5176.977  5194.228
191     192.0    5214.181  5230.597
192     193.0    5230.797  5236.537
193     194.0    5236.303  5242.843
194     195.0    5293.460  5304.371
195     196.0    5335.769  5335.769
196     197.0    5337.738  5338.272
197     198.0    5338.772  5340.874
198     199.0    5342.442  5351.385
199     200.0    5370.204  5375.976
200     201.0    5376.643  5395.696
201     202.0    5396.296  5397.231
202     203.0    5397.397  5405.472
203     204.0    5430.163  5440.407
204     205.0    5465.432  5465.432
205     206.0    5466.867  5474.308
206     207.0    5493.894  5541.508
207     208.0    5542.376  5542.376
208     209.0    5544.044  5555.689
209     210.0    5556.323  5557.357
210     211.0    5558.526  5618.018
211     212.0    5620.387  5630.397
212     213.0    5630.998  5644.344
213     214.0    5645.412  5698.165
214     215.0    5716.683  5717.918
215     216.0    5737.371  5747.581
216     217.0    5748.215  5750.684
217     218.0    5757.457  5765.365
218     219.0    5767.034  5771.405
219     220.0    5794.461  5833.200
220     221.0    5835.335  5839.006
221     222.0    5866.700  5896.964
222     223.0    5898.265  5912.346
223     224.0    5946.413  5990.591
224     225.0    6021.688  6022.723
225     226.0    6029.362  6029.462
226     227.0    6080.147  6080.147
227     228.0    6084.585  6084.585
228     229.0    6091.859  6103.703
229     230.0    6117.084  6117.084
230     231.0    6127.628  6128.028
231     232.0    6128.328  6131.164
232     233.0    6140.207  6163.430
233     234.0    6165.299  6165.299
234     235.0    6168.368  6173.874
235     236.0    6174.708  6174.708
236     237.0    6176.243  6179.613
237     238.0    6180.714  6182.816
238     239.0    6193.660  6219.286
239     240.0    6241.875  6272.906
240     241.0    6275.442  6307.207
241     242.0    6310.978  6313.313
242     243.0    6314.047  6337.938
243     244.0    6339.540  6340.374
244     245.0    6361.795  6370.037
245     246.0    6383.383  6394.928
246     247.0    6397.364  6399.499
247     248.0    6404.605  6468.135
248     249.0    6492.426  6519.820
249     250.0    6530.197  6562.629
250     251.0    6563.363  6565.199
251     252.0    6565.199  6587.821
252     253.0    6589.857  6652.819
253     254.0    6654.654  6669.937
254     255.0    6671.839  6685.185
255     256.0    6707.541  6726.560
256     257.0    6729.863  6750.050
257     258.0    6750.951  6759.726
258     259.0    6778.946  6794.461
259     260.0    6814.915  6831.632
260     261.0    6833.133  6847.514
261     262.0    6864.598  6881.481
262     263.0    7004.905  7030.430
263     264.0    7096.263  7137.004
264     265.0    7160.327  7196.330
265     266.0    7219.686  7219.686
266     267.0    7221.555  7230.297
267     268.0    7231.999  7236.003
268     269.0    7238.772  7286.652
269     270.0    7290.190  7291.625
270     271.0    7296.029  7297.030
271     272.0    7300.601  7393.660
272     273.0    7393.660  7401.535
273     274.0    7407.074  7431.431
274     275.0    7431.398  7434.067
275     276.0    7436.436  7446.246
276     277.0    7495.195  7498.799
277     278.0    7499.833  7507.274
278     279.0    7507.241  7511.011
279     280.0    7517.150  7523.524
280     281.0    7526.760  7557.524
281     282.0    7606.640  7616.216
282     283.0    7641.375  7655.355
283     284.0    7679.780  7683.083
284     285.0    7683.884  7684.685
285     286.0    7686.220  7689.890
286     287.0    7689.890  7689.890
287     288.0    7691.625  7695.229
288     289.0    7695.229  7707.007
289     290.0    7727.160  7727.160
290     291.0    7728.929  7733.734
291     292.0    7734.401  7735.435
292     293.0    7737.838  7744.411
293     294.0    7745.145  7745.145
294     295.0    7747.414  7758.792
295     296.0    7838.739  7877.778
296     297.0    7878.745  7884.685
297     298.0    7894.928  7894.928
298     299.0    7919.653  7923.023
299     300.0    7930.898  7937.104
300     301.0    7938.238  7938.939
301     302.0    7966.733  7982.115
302     303.0    8004.505  8008.308
303     304.0    8017.818  8017.818
304     305.0    8019.987  8028.317
305     306.0    8071.338  8079.913
306     307.0    8117.518  8117.518
307     308.0    8154.388  8154.388
308     309.0    8198.999  8199.366
309     310.0    8249.983  8249.983
310     311.0    8288.889  8288.889
311     312.0    8337.437  8337.437
312     313.0    8380.714  8380.714
313     314.0    8425.325  8425.325
314     315.0    8473.240  8473.240

In [14]:
tracking_frames = []
with bz2.open('FIFA World Cup 2022/Tracking Data/10510.jsonl.bz2', 'rt') as f:
    for line in f:
        if line.strip():
            tracking_frames.append(json.loads(line))

tracking_frames = sorted(tracking_frames, key=lambda x: x['videoTimeMs'])

In [15]:
tracking_df = pd.DataFrame(tracking_frames)

# Get a detailed summary (column names, non-null counts, data types)
tracking_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 171128 entries, 0 to 171127
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   version              1 non-null       str
 1   gameRefId            1 non-null       float64
 2   generatedTime        1 non-null       str
 3   smoothedTime         1 non-null       str
 4   videoTimeMs          171128 non-null  float64
 5   frameNum             171128 non-null  int64
 6   period               171128 non-null  int64
 7   periodElapsedTime    171128 non-null  float64
 8   periodGameClockTime  171128 non-null  float64
 9   homePlayers          171128 non-null  object
 10  homePlayersSmoothed  171127 non-null  object
 11  awayPlayers          171128 non-null  object
 12  awayPlayersSmoothed  171127 non-null  object
 13  balls                171128 non-null  object
 14  ballsSmoothed        127781 non-null  object
 15  game_event_id        62053 non-null   float64
 16  possession_event_id  1846 non-null    float64
 17  game_event           62053 non-null   object
 18  possession_event     1846 non-null    object
dtypes: float64(6), int64(2), object(8), str(3)
memory usage: 24.8+ MB

In [16]:
# 1. Expand the list of dictionaries into a separate DataFrame
expanded_df = pd.json_normalize(tracking_df['game_event'])

# 2. Drop columns where ALL values are NaN/None
expanded_df = expanded_df.dropna(axis=1, how='all')

# 3. Print the value counts for the remaining valid columns
for col in expanded_df.columns:
    if len(expanded_df[col].value_counts(dropna=True)) > 11:
        continue
    print(f"========== {col} ==========")
    print(expanded_df[col].value_counts(dropna=True))
    print("\n")

========== game_id ==========
game_id
10510.0    62053
Name: count, dtype: int64


========== game_event_type ==========
game_event_type
OTB              61948
OUT                 81
SUB                 21
FIRSTKICKOFF         1
END                  1
SECONDKICKOFF        1
Name: count, dtype: int64


========== position_group_type ==========
position_group_type
CM     15382
RCB     8930
LCB     7142
RW      5978
GK      5626
RB      5566
AM      4437
LB      4308
LW      2516
CF      2059
Name: count, dtype: int64


========== team_id ==========
team_id
371    31299
361    30669
Name: count, dtype: int64


========== team_name ==========
team_name
Croatia    31299
Brazil     30669
Name: count, dtype: int64


========== home_team ==========
home_team
1.0    31299
0.0    30669
Name: count, dtype: int64


========== home_ball ==========
home_ball
True     31369
False    30663
Name: count, dtype: int64

In [17]:
# 1. Expand the list of dictionaries into a separate DataFrame
expanded_df = pd.json_normalize(tracking_df['possession_event'])

# 2. Drop columns where ALL values are NaN/None
expanded_df = expanded_df.dropna(axis=1, how='all')

# 3. Print the value counts for the remaining valid columns
for col in expanded_df.columns:
    if len(expanded_df[col].value_counts(dropna=True)) > 11:
        continue
    print(f"========== {col} ==========")
    print(expanded_df[col].value_counts(dropna=True))
    print("\n")

========== game_id ==========
game_id
10510.0    1846
Name: count, dtype: int64


========== possession_event_type ==========
possession_event_type
PA    1276
CH     353
CL      63
RE      49
SH      37
BC      36
CR      32
Name: count, dtype: int64


========== updated_at ==========
updated_at
2022-12-09T22:16:08    296
2022-12-09T22:16:09    294
2022-12-09T22:16:07    276
2022-12-09T22:16:11    263
2022-12-09T22:16:12    253
2022-12-09T22:16:10    239
2022-12-09T22:16:06    190
2022-12-09T22:16:13     32
2022-12-14T01:31:20      3
Name: count, dtype: int64

In [18]:
tracking_df['homePlayers'][1]

[{'jerseyNum': '8',
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': -3.403,
  'y': 10.421,
  'speed': 0.113},
 {'jerseyNum': '1',
  'confidence': 'LOW',
  'visibility': 'ESTIMATED',
  'x': -39.676,
  'y': 0.239,
  'speed': 0.485},
 {'jerseyNum': '22',
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': -0.067,
  'y': -28.14,
  'speed': 1.029},
 {'jerseyNum': '10',
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': 0.36,
  'y': 0.301,
  'speed': 0.834},
 {'jerseyNum': '6',
  'confidence': 'LOW',
  'visibility': 'ESTIMATED',
  'x': -16.699,
  'y': -6.778,
  'speed': 0.822},
 {'jerseyNum': '9',
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': 1.297,
  'y': -12.058,
  'speed': 1.37},
 {'jerseyNum': '20',
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': -19.141,
  'y': 6.019,
  'speed': 0.353},
 {'jerseyNum': '19',
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': -14.073,
  'y': 21.845,
  'speed': 0.267},
 {'jerseyNum': '11',
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': -10.857,
  'y': 1.182,
  'speed': 0.033},
 {'jerseyNum': '4',
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': -0.331,
  'y': 15.981,
  'speed': 0.702},
 {'jerseyNum': '15',
  'confidence': 'HIGH',
  'visibility': 'VISIBLE',
  'x': 0.817,
  'y': -19.843,
  'speed': 1.447}]

In [19]:
tracking_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 171128 entries, 0 to 171127
Data columns (total 19 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   version              1 non-null       str
 1   gameRefId            1 non-null       float64
 2   generatedTime        1 non-null       str
 3   smoothedTime         1 non-null       str
 4   videoTimeMs          171128 non-null  float64
 5   frameNum             171128 non-null  int64
 6   period               171128 non-null  int64
 7   periodElapsedTime    171128 non-null  float64
 8   periodGameClockTime  171128 non-null  float64
 9   homePlayers          171128 non-null  object
 10  homePlayersSmoothed  171127 non-null  object
 11  awayPlayers          171128 non-null  object
 12  awayPlayersSmoothed  171127 non-null  object
 13  balls                171128 non-null  object
 14  ballsSmoothed        127781 non-null  object
 15  game_event_id        62053 non-null   float64
 16  possession_event_id  1846 non-null    float64
 17  game_event           62053 non-null   object
 18  possession_event     1846 non-null    object
dtypes: float64(6), int64(2), object(8), str(3)
memory usage: 24.8+ MB

In [20]:
print(tracking_df[tracking_df['game_event_id'] == 6662582]['frameNum'])
#9874
print(tracking_df[tracking_df['game_event_id'] == 6662585][['frameNum','game_event_id']])
#10326

4470    9874
Name: frameNum, dtype: int64
      frameNum  game_event_id
4500      9904      6662585.0
4501      9905      6662585.0
4502      9906      6662585.0
4503      9907      6662585.0
4504      9908      6662585.0
4505      9909      6662585.0
4506      9910      6662585.0
4507      9911      6662585.0
4508      9912      6662585.0
4509      9913      6662585.0
4510      9914      6662585.0
4511      9915      6662585.0
4512      9916      6662585.0
4513      9917      6662585.0
4514      9918      6662585.0
4515      9919      6662585.0
4516      9920      6662585.0
4517      9921      6662585.0
4518      9922      6662585.0
4519      9923      6662585.0
4520      9924      6662585.0
4521      9925      6662585.0
4522      9926      6662585.0
4523      9927      6662585.0
4524      9928      6662585.0
4525      9929      6662585.0
4526      9930      6662585.0
4527      9931      6662585.0
4528      9932      6662585.0
4529      9933      6662585.0
4530      9934      6662585.0
4531      9935      6662585.0
4532      9936      6662585.0
4533      9937      6662585.0
4534      9938      6662585.0
4535      9939      6662585.0
4536      9940      6662585.0

In [21]:
for i in range(77,85):
    print(events_df['sequence'][i])
    print(events_df['startTime'][i])
    print(events_df['endTime'][i])
    print(events_df['gameEventId'][i])
    print(events_df['gameEvents'][i].get('gameEventType'))
    print(events_df['possessionEvents'][i].get('possessionEventType'))
    print(events_df['eventTime'][i])
    print("----------------------------")

10.0
329.463
329.463
6662582
OTB
PA
329.463
----------------------------
10.0
330.464
331.665
6662585
OTB
IT
330.464
----------------------------
10.0
330.464
331.665
6662585
OTB
CR
331.665
----------------------------
10.0
333.133
333.133
6662591
OTB
CL
333.133
----------------------------
10.0
334.768
334.768
6662601
OTB
PA
334.768
----------------------------
10.0
338.906
338.939
6662606
OTB
PA
338.939
----------------------------
10.0
343.043
344.545
6662611
OTB
IT
343.043
----------------------------
10.0
343.043
344.545
6662611
OTB
PA
344.545
----------------------------